### ISSUE TITLE
Invalid frequency passed to pd.Grouper

### ISSUE THREAD

**Issue by mathilde-ritman** [martinvonk/SPEI#38]
Invalid frequency string passed to pd.Grouper. 

The group_yearly_df function passes either "YE" or "Y" to pd.Grouper, depending on the pandas version. Using pandas version '2.1.4', the frequency passed to pd.Grouper is invalid. The correct string is "Y", but "YE" is passed.

The following error was caused:

> File ~/.local/lib/python3.10/site-packages/spei/utils.py:85, in group_yearly_df(series)
>      83 grs = {}
>      84 freq = "YE" if pd_version >= "2.1.0" else "Y"
> ---> 85 for year_timestamp, gry in series.groupby(Grouper(freq=freq)):
>      86     index = validate_index(gry.index)
>      87     gry.index = to_datetime(
>      88         "2000-" + index.strftime(strfstr), format="%Y-" + strfstr
>      89     )
> 
> File /g/data/hh5/public/apps/miniconda3/envs/analysis3-23.10/lib/python3.10/site-packages/pandas/core/resample.py:2046, in TimeGrouper.__init__(self, freq, closed, label, how, axis, fill_method, limit, kind, convention, origin, offset, group_keys, **kwargs)
>    2043 if convention not in {None, "start", "end", "e", "s"}:
>    2044     raise ValueError(f"Unsupported value {convention} for `convention`")
> -> 2046 freq = to_offset(freq)
>    2048 end_types = {"M", "A", "Q", "BM", "BA", "BQ", "W"}
>    2049 rule = freq.rule_code
> 
> File offsets.pyx:4460, in pandas._libs.tslibs.offsets.to_offset()
> 
> File offsets.pyx:4557, in pandas._libs.tslibs.offsets.to_offset()
> 
> ValueError: Invalid frequency: YE

**Comment by martinvonk** [comment]
Hi @mathilde-ritman,

I pushed [bdba99c](https://github.com/martinvonk/SPEI/commit/bdba99ceaa3a7a2949c30e5942994fe7c00512c7) to the dev branch. Does that solve your issue?

**Comment by mathilde-ritman** [comment]
Thanks! Works great.
