### ISSUE TITLE
Invalid frequency: ME

### ISSUE THREAD

**Issue by Mahsabzg** [martinvonk/SPEI#42]
I have daily precipitation data. I followed the steps in the examples, but I faced this error: 'Invalid frequency: ME'. I appreciate it if you guide me about the possible problem.

**Comment by martinvonk** [comment]
This is probably related to your pandas version. Pandas updated its frequency aliases recently: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases
